-- MySQL Script generated by MySQL Workbench
-- Fri Mar 25 16:33:08 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_dxsj
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_dxsj` ;

-- -----------------------------------------------------
-- Schema db_dxsj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_dxsj` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `db_dxsj` ;

-- -----------------------------------------------------
-- Table `db_dxsj`.`tab_cases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dxsj`.`tab_cases` ;

CREATE TABLE IF NOT EXISTS `db_dxsj`.`tab_cases` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `title` VARCHAR(1000) NULL,
  `content_path` VARCHAR(1000) NULL COMMENT '内容所在目录',
  `preview` VARCHAR(200) NULL DEFAULT 'preview.jpg' COMMENT '预览图图片名称',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `tab_cases_updatetime_index` (`update_time` DESC));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `db_dxsj`;

DELIMITER $$

USE `db_dxsj`$$
DROP TRIGGER IF EXISTS `db_dxsj`.`tab_cases_BEFORE_INSERT` $$
USE `db_dxsj`$$
CREATE DEFINER = CURRENT_USER TRIGGER `db_dxsj`.`tab_cases_BEFORE_INSERT` BEFORE INSERT ON `tab_cases` FOR EACH ROW
BEGIN
set @temp_now = now(); set new.`create_time` = @temp_now ; set new.`update_time` = @temp_now ;
END$$


USE `db_dxsj`$$
DROP TRIGGER IF EXISTS `db_dxsj`.`tab_cases_BEFORE_UPDATE` $$
USE `db_dxsj`$$
CREATE DEFINER = CURRENT_USER TRIGGER `db_dxsj`.`tab_cases_BEFORE_UPDATE` BEFORE UPDATE ON `tab_cases` FOR EACH ROW
BEGIN
set new.`update_time` = now() ;
END$$


DELIMITER ;
