-- MySQL Script generated by MySQL Workbench
-- Sun Mar 13 13:42:32 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- user user_dxsj
-- -----------------------------------------------------
DROP USER IF EXISTS `user_dxsj`@`localhost`;
DROP USER IF EXISTS `user_dxsj`@`%`;
CREATE USER `user_dxsj`@`%` IDENTIFIED by 'yytest';
GRANT all privileges ON `db_dxsj`.* TO `user_dxsj`@`%`;

FLUSH privileges;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Table `db_tzthfdc`.`Tab_User` data yytest
-- -----------------------------------------------------
-- dxsj123
INSERT INTO `db_dxsj`.`Tab_User`(`user_name`, `password`, `salt`) VALUES ('admin', '58302b997d1195b9633282fbfd81615c', 'HIrVeF');

INSERT INTO `db_dxsj`.`tab_website_info`(`domain`, `com_name`, `website_name`, `com_address`, `com_postcode`, `contact`, `com_keywords`, `com_description`, `com_service_aim`, `com_service_aim_desc`, `com_desire`, `beian_url`, `beian_no`, `website_home_bg`) VALUES ('dx-sj.com', '泰兴鼎鑫设计装饰有限公司', '鼎鑫设计装饰', '江苏省泰兴市济川路12号3楼', '225400', '0523-87781789', '', '', '', '', '', 'http://www.miitbeian.gov.cn/', '苏ICP备16009335号-1', 'public/img/home-gallery-1.jpg');

