-- MySQL Script generated by MySQL Workbench
-- Sun Mar 13 13:42:32 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- user user_dxsj
-- -----------------------------------------------------
DROP USER IF EXISTS `user_dxsj`@`localhost`;
DROP USER IF EXISTS `user_dxsj`@`%`;
CREATE USER `user_dxsj`@`%` IDENTIFIED by 'yytest';
GRANT all privileges ON `db_dxsj`.* TO `user_dxsj`@`%`;

FLUSH privileges;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;